// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: gateway/v1/gateway.proto

package gatewaypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Gateway int32

const (
	Gateway_GATEWAY_UNSPECIFIED Gateway = 0
	Gateway_GATEWAY_RAZORPAY    Gateway = 1
	Gateway_GATEWAY_STRIPE      Gateway = 2
	Gateway_GATEWAY_CASHFREE    Gateway = 3
	Gateway_GATEWAY_PAYPAL      Gateway = 4
)

// Enum value maps for Gateway.
var (
	Gateway_name = map[int32]string{
		0: "GATEWAY_UNSPECIFIED",
		1: "GATEWAY_RAZORPAY",
		2: "GATEWAY_STRIPE",
		3: "GATEWAY_CASHFREE",
		4: "GATEWAY_PAYPAL",
	}
	Gateway_value = map[string]int32{
		"GATEWAY_UNSPECIFIED": 0,
		"GATEWAY_RAZORPAY":    1,
		"GATEWAY_STRIPE":      2,
		"GATEWAY_CASHFREE":    3,
		"GATEWAY_PAYPAL":      4,
	}
)

func (x Gateway) Enum() *Gateway {
	p := new(Gateway)
	*p = x
	return p
}

func (x Gateway) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Gateway) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[0].Descriptor()
}

func (Gateway) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[0]
}

func (x Gateway) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Gateway.Descriptor instead.
func (Gateway) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

type Currency int32

const (
	Currency_CURRENCY_UNSPECIFIED Currency = 0
	Currency_CURRENCY_INR         Currency = 1
	Currency_CURRENCY_USD         Currency = 2
	Currency_CURRENCY_EUR         Currency = 3
	Currency_CURRENCY_GBP         Currency = 4
	Currency_CURRENCY_AED         Currency = 5
	Currency_CURRENCY_SGD         Currency = 6
)

// Enum value maps for Currency.
var (
	Currency_name = map[int32]string{
		0: "CURRENCY_UNSPECIFIED",
		1: "CURRENCY_INR",
		2: "CURRENCY_USD",
		3: "CURRENCY_EUR",
		4: "CURRENCY_GBP",
		5: "CURRENCY_AED",
		6: "CURRENCY_SGD",
	}
	Currency_value = map[string]int32{
		"CURRENCY_UNSPECIFIED": 0,
		"CURRENCY_INR":         1,
		"CURRENCY_USD":         2,
		"CURRENCY_EUR":         3,
		"CURRENCY_GBP":         4,
		"CURRENCY_AED":         5,
		"CURRENCY_SGD":         6,
	}
)

func (x Currency) Enum() *Currency {
	p := new(Currency)
	*p = x
	return p
}

func (x Currency) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Currency) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[1].Descriptor()
}

func (Currency) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[1]
}

func (x Currency) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Currency.Descriptor instead.
func (Currency) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

type PaymentStatus int32

const (
	PaymentStatus_PAYMENT_STATUS_UNSPECIFIED PaymentStatus = 0
	PaymentStatus_PAYMENT_STATUS_PENDING     PaymentStatus = 1
	PaymentStatus_PAYMENT_STATUS_CAPTURED    PaymentStatus = 2
	PaymentStatus_PAYMENT_STATUS_FAILED      PaymentStatus = 3
	PaymentStatus_PAYMENT_STATUS_EXPIRED     PaymentStatus = 4
)

// Enum value maps for PaymentStatus.
var (
	PaymentStatus_name = map[int32]string{
		0: "PAYMENT_STATUS_UNSPECIFIED",
		1: "PAYMENT_STATUS_PENDING",
		2: "PAYMENT_STATUS_CAPTURED",
		3: "PAYMENT_STATUS_FAILED",
		4: "PAYMENT_STATUS_EXPIRED",
	}
	PaymentStatus_value = map[string]int32{
		"PAYMENT_STATUS_UNSPECIFIED": 0,
		"PAYMENT_STATUS_PENDING":     1,
		"PAYMENT_STATUS_CAPTURED":    2,
		"PAYMENT_STATUS_FAILED":      3,
		"PAYMENT_STATUS_EXPIRED":     4,
	}
)

func (x PaymentStatus) Enum() *PaymentStatus {
	p := new(PaymentStatus)
	*p = x
	return p
}

func (x PaymentStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PaymentStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[2].Descriptor()
}

func (PaymentStatus) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[2]
}

func (x PaymentStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PaymentStatus.Descriptor instead.
func (PaymentStatus) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

type RefundStatus int32

const (
	RefundStatus_REFUND_STATUS_UNSPECIFIED RefundStatus = 0
	RefundStatus_REFUND_STATUS_PENDING     RefundStatus = 1
	RefundStatus_REFUND_STATUS_PROCESSED   RefundStatus = 2
	RefundStatus_REFUND_STATUS_FAILED      RefundStatus = 3
)

// Enum value maps for RefundStatus.
var (
	RefundStatus_name = map[int32]string{
		0: "REFUND_STATUS_UNSPECIFIED",
		1: "REFUND_STATUS_PENDING",
		2: "REFUND_STATUS_PROCESSED",
		3: "REFUND_STATUS_FAILED",
	}
	RefundStatus_value = map[string]int32{
		"REFUND_STATUS_UNSPECIFIED": 0,
		"REFUND_STATUS_PENDING":     1,
		"REFUND_STATUS_PROCESSED":   2,
		"REFUND_STATUS_FAILED":      3,
	}
)

func (x RefundStatus) Enum() *RefundStatus {
	p := new(RefundStatus)
	*p = x
	return p
}

func (x RefundStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RefundStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_gateway_v1_gateway_proto_enumTypes[3].Descriptor()
}

func (RefundStatus) Type() protoreflect.EnumType {
	return &file_gateway_v1_gateway_proto_enumTypes[3]
}

func (x RefundStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RefundStatus.Descriptor instead.
func (RefundStatus) EnumDescriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

type CreateOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	AmountMinor   int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency      Currency               `protobuf:"varint,4,opt,name=currency,proto3,enum=payrail.gateway.v1.Currency" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrderRequest) Reset() {
	*x = CreateOrderRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderRequest) ProtoMessage() {}

func (x *CreateOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderRequest.ProtoReflect.Descriptor instead.
func (*CreateOrderRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrderRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *CreateOrderRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateOrderRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CreateOrderRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type CreateOrderResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GatewayOrderId string                 `protobuf:"bytes,1,opt,name=gateway_order_id,json=gatewayOrderId,proto3" json:"gateway_order_id,omitempty"`
	ClientParams   map[string]string      `protobuf:"bytes,2,rep,name=client_params,json=clientParams,proto3" json:"client_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateOrderResponse) Reset() {
	*x = CreateOrderResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrderResponse) ProtoMessage() {}

func (x *CreateOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrderResponse.ProtoReflect.Descriptor instead.
func (*CreateOrderResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrderResponse) GetGatewayOrderId() string {
	if x != nil {
		return x.GatewayOrderId
	}
	return ""
}

func (x *CreateOrderResponse) GetClientParams() map[string]string {
	if x != nil {
		return x.ClientParams
	}
	return nil
}

type VerifyWebhookRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gateway       Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	Body          []byte                 `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebhookRequest) Reset() {
	*x = VerifyWebhookRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookRequest) ProtoMessage() {}

func (x *VerifyWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookRequest.ProtoReflect.Descriptor instead.
func (*VerifyWebhookRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyWebhookRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *VerifyWebhookRequest) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *VerifyWebhookRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type VerifyWebhookResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Verified      bool                   `protobuf:"varint,1,opt,name=verified,proto3" json:"verified,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyWebhookResponse) Reset() {
	*x = VerifyWebhookResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyWebhookResponse) ProtoMessage() {}

func (x *VerifyWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyWebhookResponse.ProtoReflect.Descriptor instead.
func (*VerifyWebhookResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyWebhookResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

type FetchPaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Gateway        Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	GatewayOrderId string                 `protobuf:"bytes,2,opt,name=gateway_order_id,json=gatewayOrderId,proto3" json:"gateway_order_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FetchPaymentRequest) Reset() {
	*x = FetchPaymentRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPaymentRequest) ProtoMessage() {}

func (x *FetchPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPaymentRequest.ProtoReflect.Descriptor instead.
func (*FetchPaymentRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *FetchPaymentRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *FetchPaymentRequest) GetGatewayOrderId() string {
	if x != nil {
		return x.GatewayOrderId
	}
	return ""
}

type FetchPaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           PaymentStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=payrail.gateway.v1.PaymentStatus" json:"status,omitempty"`
	GatewayPaymentId string                 `protobuf:"bytes,2,opt,name=gateway_payment_id,json=gatewayPaymentId,proto3" json:"gateway_payment_id,omitempty"`
	AmountMinor      int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency         Currency               `protobuf:"varint,4,opt,name=currency,proto3,enum=payrail.gateway.v1.Currency" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *FetchPaymentResponse) Reset() {
	*x = FetchPaymentResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchPaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchPaymentResponse) ProtoMessage() {}

func (x *FetchPaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchPaymentResponse.ProtoReflect.Descriptor instead.
func (*FetchPaymentResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{5}
}

func (x *FetchPaymentResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *FetchPaymentResponse) GetGatewayPaymentId() string {
	if x != nil {
		return x.GatewayPaymentId
	}
	return ""
}

func (x *FetchPaymentResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *FetchPaymentResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type FetchRefundRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Gateway         Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	GatewayRefundId string                 `protobuf:"bytes,2,opt,name=gateway_refund_id,json=gatewayRefundId,proto3" json:"gateway_refund_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchRefundRequest) Reset() {
	*x = FetchRefundRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRefundRequest) ProtoMessage() {}

func (x *FetchRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRefundRequest.ProtoReflect.Descriptor instead.
func (*FetchRefundRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{6}
}

func (x *FetchRefundRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *FetchRefundRequest) GetGatewayRefundId() string {
	if x != nil {
		return x.GatewayRefundId
	}
	return ""
}

func (x *FetchRefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type FetchRefundResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          RefundStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=payrail.gateway.v1.RefundStatus" json:"status,omitempty"`
	GatewayRefundId string                 `protobuf:"bytes,2,opt,name=gateway_refund_id,json=gatewayRefundId,proto3" json:"gateway_refund_id,omitempty"`
	AmountMinor     int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FetchRefundResponse) Reset() {
	*x = FetchRefundResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRefundResponse) ProtoMessage() {}

func (x *FetchRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRefundResponse.ProtoReflect.Descriptor instead.
func (*FetchRefundResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{7}
}

func (x *FetchRefundResponse) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNSPECIFIED
}

func (x *FetchRefundResponse) GetGatewayRefundId() string {
	if x != nil {
		return x.GatewayRefundId
	}
	return ""
}

func (x *FetchRefundResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

type CaptureRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gateway          Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	GatewayPaymentId string                 `protobuf:"bytes,2,opt,name=gateway_payment_id,json=gatewayPaymentId,proto3" json:"gateway_payment_id,omitempty"`
	AmountMinor      int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency         Currency               `protobuf:"varint,4,opt,name=currency,proto3,enum=payrail.gateway.v1.Currency" json:"currency,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureRequest) Reset() {
	*x = CaptureRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureRequest) ProtoMessage() {}

func (x *CaptureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureRequest.ProtoReflect.Descriptor instead.
func (*CaptureRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{8}
}

func (x *CaptureRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *CaptureRequest) GetGatewayPaymentId() string {
	if x != nil {
		return x.GatewayPaymentId
	}
	return ""
}

func (x *CaptureRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CaptureRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

type CaptureResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Status           PaymentStatus          `protobuf:"varint,1,opt,name=status,proto3,enum=payrail.gateway.v1.PaymentStatus" json:"status,omitempty"`
	GatewayPaymentId string                 `protobuf:"bytes,2,opt,name=gateway_payment_id,json=gatewayPaymentId,proto3" json:"gateway_payment_id,omitempty"`
	AmountMinor      int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CaptureResponse) Reset() {
	*x = CaptureResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CaptureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CaptureResponse) ProtoMessage() {}

func (x *CaptureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CaptureResponse.ProtoReflect.Descriptor instead.
func (*CaptureResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{9}
}

func (x *CaptureResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *CaptureResponse) GetGatewayPaymentId() string {
	if x != nil {
		return x.GatewayPaymentId
	}
	return ""
}

func (x *CaptureResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

type CreateRefundRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Gateway          Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	GatewayPaymentId string                 `protobuf:"bytes,2,opt,name=gateway_payment_id,json=gatewayPaymentId,proto3" json:"gateway_payment_id,omitempty"`
	AmountMinor      int64                  `protobuf:"varint,3,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency         Currency               `protobuf:"varint,4,opt,name=currency,proto3,enum=payrail.gateway.v1.Currency" json:"currency,omitempty"`
	IdempotencyKey   string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateRefundRequest) Reset() {
	*x = CreateRefundRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundRequest) ProtoMessage() {}

func (x *CreateRefundRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundRequest.ProtoReflect.Descriptor instead.
func (*CreateRefundRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{10}
}

func (x *CreateRefundRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *CreateRefundRequest) GetGatewayPaymentId() string {
	if x != nil {
		return x.GatewayPaymentId
	}
	return ""
}

func (x *CreateRefundRequest) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *CreateRefundRequest) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

func (x *CreateRefundRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CreateRefundResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Status          RefundStatus           `protobuf:"varint,1,opt,name=status,proto3,enum=payrail.gateway.v1.RefundStatus" json:"status,omitempty"`
	GatewayRefundId string                 `protobuf:"bytes,2,opt,name=gateway_refund_id,json=gatewayRefundId,proto3" json:"gateway_refund_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateRefundResponse) Reset() {
	*x = CreateRefundResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRefundResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRefundResponse) ProtoMessage() {}

func (x *CreateRefundResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRefundResponse.ProtoReflect.Descriptor instead.
func (*CreateRefundResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{11}
}

func (x *CreateRefundResponse) GetStatus() RefundStatus {
	if x != nil {
		return x.Status
	}
	return RefundStatus_REFUND_STATUS_UNSPECIFIED
}

func (x *CreateRefundResponse) GetGatewayRefundId() string {
	if x != nil {
		return x.GatewayRefundId
	}
	return ""
}

type FindOrderByReferenceRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Gateway           Gateway                `protobuf:"varint,1,opt,name=gateway,proto3,enum=payrail.gateway.v1.Gateway" json:"gateway,omitempty"`
	MerchantReference string                 `protobuf:"bytes,2,opt,name=merchant_reference,json=merchantReference,proto3" json:"merchant_reference,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *FindOrderByReferenceRequest) Reset() {
	*x = FindOrderByReferenceRequest{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderByReferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderByReferenceRequest) ProtoMessage() {}

func (x *FindOrderByReferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderByReferenceRequest.ProtoReflect.Descriptor instead.
func (*FindOrderByReferenceRequest) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{12}
}

func (x *FindOrderByReferenceRequest) GetGateway() Gateway {
	if x != nil {
		return x.Gateway
	}
	return Gateway_GATEWAY_UNSPECIFIED
}

func (x *FindOrderByReferenceRequest) GetMerchantReference() string {
	if x != nil {
		return x.MerchantReference
	}
	return ""
}

type FindOrderByReferenceResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Found          bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	GatewayOrderId string                 `protobuf:"bytes,2,opt,name=gateway_order_id,json=gatewayOrderId,proto3" json:"gateway_order_id,omitempty"`
	Status         PaymentStatus          `protobuf:"varint,3,opt,name=status,proto3,enum=payrail.gateway.v1.PaymentStatus" json:"status,omitempty"`
	AmountMinor    int64                  `protobuf:"varint,4,opt,name=amount_minor,json=amountMinor,proto3" json:"amount_minor,omitempty"`
	Currency       Currency               `protobuf:"varint,5,opt,name=currency,proto3,enum=payrail.gateway.v1.Currency" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *FindOrderByReferenceResponse) Reset() {
	*x = FindOrderByReferenceResponse{}
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindOrderByReferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindOrderByReferenceResponse) ProtoMessage() {}

func (x *FindOrderByReferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_v1_gateway_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindOrderByReferenceResponse.ProtoReflect.Descriptor instead.
func (*FindOrderByReferenceResponse) Descriptor() ([]byte, []int) {
	return file_gateway_v1_gateway_proto_rawDescGZIP(), []int{13}
}

func (x *FindOrderByReferenceResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

func (x *FindOrderByReferenceResponse) GetGatewayOrderId() string {
	if x != nil {
		return x.GatewayOrderId
	}
	return ""
}

func (x *FindOrderByReferenceResponse) GetStatus() PaymentStatus {
	if x != nil {
		return x.Status
	}
	return PaymentStatus_PAYMENT_STATUS_UNSPECIFIED
}

func (x *FindOrderByReferenceResponse) GetAmountMinor() int64 {
	if x != nil {
		return x.AmountMinor
	}
	return 0
}

func (x *FindOrderByReferenceResponse) GetCurrency() Currency {
	if x != nil {
		return x.Currency
	}
	return Currency_CURRENCY_UNSPECIFIED
}

var File_gateway_v1_gateway_proto protoreflect.FileDescriptor

const file_gateway_v1_gateway_proto_rawDesc = "" +
	"\n" +
	"\x18gateway/v1/gateway.proto\x12\x12payrail.gateway.v1\"\xc3\x01\n" +
	"\x12CreateOrderRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x128\n" +
	"\bcurrency\x18\x04 \x01(\x0e2\x1c.payrail.gateway.v1.CurrencyR\bcurrency\"\xe0\x01\n" +
	"\x13CreateOrderResponse\x12(\n" +
	"\x10gateway_order_id\x18\x01 \x01(\tR\x0egatewayOrderId\x12^\n" +
	"\rclient_params\x18\x02 \x03(\v29.payrail.gateway.v1.CreateOrderResponse.ClientParamsEntryR\fclientParams\x1a?\n" +
	"\x11ClientParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xee\x01\n" +
	"\x14VerifyWebhookRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12\x12\n" +
	"\x04body\x18\x02 \x01(\fR\x04body\x12O\n" +
	"\aheaders\x18\x03 \x03(\v25.payrail.gateway.v1.VerifyWebhookRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\x15VerifyWebhookResponse\x12\x1a\n" +
	"\bverified\x18\x01 \x01(\bR\bverified\"v\n" +
	"\x13FetchPaymentRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12(\n" +
	"\x10gateway_order_id\x18\x02 \x01(\tR\x0egatewayOrderId\"\xdc\x01\n" +
	"\x14FetchPaymentResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.payrail.gateway.v1.PaymentStatusR\x06status\x12,\n" +
	"\x12gateway_payment_id\x18\x02 \x01(\tR\x10gatewayPaymentId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x128\n" +
	"\bcurrency\x18\x04 \x01(\x0e2\x1c.payrail.gateway.v1.CurrencyR\bcurrency\"\xa0\x01\n" +
	"\x12FetchRefundRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12*\n" +
	"\x11gateway_refund_id\x18\x02 \x01(\tR\x0fgatewayRefundId\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"\x9e\x01\n" +
	"\x13FetchRefundResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .payrail.gateway.v1.RefundStatusR\x06status\x12*\n" +
	"\x11gateway_refund_id\x18\x02 \x01(\tR\x0fgatewayRefundId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\"\xd2\x01\n" +
	"\x0eCaptureRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12,\n" +
	"\x12gateway_payment_id\x18\x02 \x01(\tR\x10gatewayPaymentId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x128\n" +
	"\bcurrency\x18\x04 \x01(\x0e2\x1c.payrail.gateway.v1.CurrencyR\bcurrency\"\x9d\x01\n" +
	"\x0fCaptureResponse\x129\n" +
	"\x06status\x18\x01 \x01(\x0e2!.payrail.gateway.v1.PaymentStatusR\x06status\x12,\n" +
	"\x12gateway_payment_id\x18\x02 \x01(\tR\x10gatewayPaymentId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\"\x80\x02\n" +
	"\x13CreateRefundRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12,\n" +
	"\x12gateway_payment_id\x18\x02 \x01(\tR\x10gatewayPaymentId\x12!\n" +
	"\famount_minor\x18\x03 \x01(\x03R\vamountMinor\x128\n" +
	"\bcurrency\x18\x04 \x01(\x0e2\x1c.payrail.gateway.v1.CurrencyR\bcurrency\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"|\n" +
	"\x14CreateRefundResponse\x128\n" +
	"\x06status\x18\x01 \x01(\x0e2 .payrail.gateway.v1.RefundStatusR\x06status\x12*\n" +
	"\x11gateway_refund_id\x18\x02 \x01(\tR\x0fgatewayRefundId\"\x83\x01\n" +
	"\x1bFindOrderByReferenceRequest\x125\n" +
	"\agateway\x18\x01 \x01(\x0e2\x1b.payrail.gateway.v1.GatewayR\agateway\x12-\n" +
	"\x12merchant_reference\x18\x02 \x01(\tR\x11merchantReference\"\xf6\x01\n" +
	"\x1cFindOrderByReferenceResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\x12(\n" +
	"\x10gateway_order_id\x18\x02 \x01(\tR\x0egatewayOrderId\x129\n" +
	"\x06status\x18\x03 \x01(\x0e2!.payrail.gateway.v1.PaymentStatusR\x06status\x12!\n" +
	"\famount_minor\x18\x04 \x01(\x03R\vamountMinor\x128\n" +
	"\bcurrency\x18\x05 \x01(\x0e2\x1c.payrail.gateway.v1.CurrencyR\bcurrency*v\n" +
	"\aGateway\x12\x17\n" +
	"\x13GATEWAY_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10GATEWAY_RAZORPAY\x10\x01\x12\x12\n" +
	"\x0eGATEWAY_STRIPE\x10\x02\x12\x14\n" +
	"\x10GATEWAY_CASHFREE\x10\x03\x12\x12\n" +
	"\x0eGATEWAY_PAYPAL\x10\x04*\x90\x01\n" +
	"\bCurrency\x12\x18\n" +
	"\x14CURRENCY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fCURRENCY_INR\x10\x01\x12\x10\n" +
	"\fCURRENCY_USD\x10\x02\x12\x10\n" +
	"\fCURRENCY_EUR\x10\x03\x12\x10\n" +
	"\fCURRENCY_GBP\x10\x04\x12\x10\n" +
	"\fCURRENCY_AED\x10\x05\x12\x10\n" +
	"\fCURRENCY_SGD\x10\x06*\x9f\x01\n" +
	"\rPaymentStatus\x12\x1e\n" +
	"\x1aPAYMENT_STATUS_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16PAYMENT_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17PAYMENT_STATUS_CAPTURED\x10\x02\x12\x19\n" +
	"\x15PAYMENT_STATUS_FAILED\x10\x03\x12\x1a\n" +
	"\x16PAYMENT_STATUS_EXPIRED\x10\x04*\x7f\n" +
	"\fRefundStatus\x12\x1d\n" +
	"\x19REFUND_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REFUND_STATUS_PENDING\x10\x01\x12\x1b\n" +
	"\x17REFUND_STATUS_PROCESSED\x10\x02\x12\x18\n" +
	"\x14REFUND_STATUS_FAILED\x10\x032\xd2\x05\n" +
	"\x0eGatewayService\x12^\n" +
	"\vCreateOrder\x12&.payrail.gateway.v1.CreateOrderRequest\x1a'.payrail.gateway.v1.CreateOrderResponse\x12d\n" +
	"\rVerifyWebhook\x12(.payrail.gateway.v1.VerifyWebhookRequest\x1a).payrail.gateway.v1.VerifyWebhookResponse\x12a\n" +
	"\fFetchPayment\x12'.payrail.gateway.v1.FetchPaymentRequest\x1a(.payrail.gateway.v1.FetchPaymentResponse\x12^\n" +
	"\vFetchRefund\x12&.payrail.gateway.v1.FetchRefundRequest\x1a'.payrail.gateway.v1.FetchRefundResponse\x12Y\n" +
	"\x0eCapturePayment\x12\".payrail.gateway.v1.CaptureRequest\x1a#.payrail.gateway.v1.CaptureResponse\x12a\n" +
	"\fCreateRefund\x12'.payrail.gateway.v1.CreateRefundRequest\x1a(.payrail.gateway.v1.CreateRefundResponse\x12y\n" +
	"\x14FindOrderByReference\x12/.payrail.gateway.v1.FindOrderByReferenceRequest\x1a0.payrail.gateway.v1.FindOrderByReferenceResponseB4Z2github.com/payrail/go/internal/gatewaypb;gatewaypbb\x06proto3"

var (
	file_gateway_v1_gateway_proto_rawDescOnce sync.Once
	file_gateway_v1_gateway_proto_rawDescData []byte
)

func file_gateway_v1_gateway_proto_rawDescGZIP() []byte {
	file_gateway_v1_gateway_proto_rawDescOnce.Do(func() {
		file_gateway_v1_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)))
	})
	return file_gateway_v1_gateway_proto_rawDescData
}

var file_gateway_v1_gateway_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_gateway_v1_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_gateway_v1_gateway_proto_goTypes = []any{
	(Gateway)(0),                         // 0: payrail.gateway.v1.Gateway
	(Currency)(0),                        // 1: payrail.gateway.v1.Currency
	(PaymentStatus)(0),                   // 2: payrail.gateway.v1.PaymentStatus
	(RefundStatus)(0),                    // 3: payrail.gateway.v1.RefundStatus
	(*CreateOrderRequest)(nil),           // 4: payrail.gateway.v1.CreateOrderRequest
	(*CreateOrderResponse)(nil),          // 5: payrail.gateway.v1.CreateOrderResponse
	(*VerifyWebhookRequest)(nil),         // 6: payrail.gateway.v1.VerifyWebhookRequest
	(*VerifyWebhookResponse)(nil),        // 7: payrail.gateway.v1.VerifyWebhookResponse
	(*FetchPaymentRequest)(nil),          // 8: payrail.gateway.v1.FetchPaymentRequest
	(*FetchPaymentResponse)(nil),         // 9: payrail.gateway.v1.FetchPaymentResponse
	(*FetchRefundRequest)(nil),           // 10: payrail.gateway.v1.FetchRefundRequest
	(*FetchRefundResponse)(nil),          // 11: payrail.gateway.v1.FetchRefundResponse
	(*CaptureRequest)(nil),               // 12: payrail.gateway.v1.CaptureRequest
	(*CaptureResponse)(nil),              // 13: payrail.gateway.v1.CaptureResponse
	(*CreateRefundRequest)(nil),          // 14: payrail.gateway.v1.CreateRefundRequest
	(*CreateRefundResponse)(nil),         // 15: payrail.gateway.v1.CreateRefundResponse
	(*FindOrderByReferenceRequest)(nil),  // 16: payrail.gateway.v1.FindOrderByReferenceRequest
	(*FindOrderByReferenceResponse)(nil), // 17: payrail.gateway.v1.FindOrderByReferenceResponse
	nil,                                  // 18: payrail.gateway.v1.CreateOrderResponse.ClientParamsEntry
	nil,                                  // 19: payrail.gateway.v1.VerifyWebhookRequest.HeadersEntry
}
var file_gateway_v1_gateway_proto_depIdxs = []int32{
	0,  // 0: payrail.gateway.v1.CreateOrderRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	1,  // 1: payrail.gateway.v1.CreateOrderRequest.currency:type_name -> payrail.gateway.v1.Currency
	18, // 2: payrail.gateway.v1.CreateOrderResponse.client_params:type_name -> payrail.gateway.v1.CreateOrderResponse.ClientParamsEntry
	0,  // 3: payrail.gateway.v1.VerifyWebhookRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	19, // 4: payrail.gateway.v1.VerifyWebhookRequest.headers:type_name -> payrail.gateway.v1.VerifyWebhookRequest.HeadersEntry
	0,  // 5: payrail.gateway.v1.FetchPaymentRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	2,  // 6: payrail.gateway.v1.FetchPaymentResponse.status:type_name -> payrail.gateway.v1.PaymentStatus
	1,  // 7: payrail.gateway.v1.FetchPaymentResponse.currency:type_name -> payrail.gateway.v1.Currency
	0,  // 8: payrail.gateway.v1.FetchRefundRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	3,  // 9: payrail.gateway.v1.FetchRefundResponse.status:type_name -> payrail.gateway.v1.RefundStatus
	0,  // 10: payrail.gateway.v1.CaptureRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	1,  // 11: payrail.gateway.v1.CaptureRequest.currency:type_name -> payrail.gateway.v1.Currency
	2,  // 12: payrail.gateway.v1.CaptureResponse.status:type_name -> payrail.gateway.v1.PaymentStatus
	0,  // 13: payrail.gateway.v1.CreateRefundRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	1,  // 14: payrail.gateway.v1.CreateRefundRequest.currency:type_name -> payrail.gateway.v1.Currency
	3,  // 15: payrail.gateway.v1.CreateRefundResponse.status:type_name -> payrail.gateway.v1.RefundStatus
	0,  // 16: payrail.gateway.v1.FindOrderByReferenceRequest.gateway:type_name -> payrail.gateway.v1.Gateway
	2,  // 17: payrail.gateway.v1.FindOrderByReferenceResponse.status:type_name -> payrail.gateway.v1.PaymentStatus
	1,  // 18: payrail.gateway.v1.FindOrderByReferenceResponse.currency:type_name -> payrail.gateway.v1.Currency
	4,  // 19: payrail.gateway.v1.GatewayService.CreateOrder:input_type -> payrail.gateway.v1.CreateOrderRequest
	6,  // 20: payrail.gateway.v1.GatewayService.VerifyWebhook:input_type -> payrail.gateway.v1.VerifyWebhookRequest
	8,  // 21: payrail.gateway.v1.GatewayService.FetchPayment:input_type -> payrail.gateway.v1.FetchPaymentRequest
	10, // 22: payrail.gateway.v1.GatewayService.FetchRefund:input_type -> payrail.gateway.v1.FetchRefundRequest
	12, // 23: payrail.gateway.v1.GatewayService.CapturePayment:input_type -> payrail.gateway.v1.CaptureRequest
	14, // 24: payrail.gateway.v1.GatewayService.CreateRefund:input_type -> payrail.gateway.v1.CreateRefundRequest
	16, // 25: payrail.gateway.v1.GatewayService.FindOrderByReference:input_type -> payrail.gateway.v1.FindOrderByReferenceRequest
	5,  // 26: payrail.gateway.v1.GatewayService.CreateOrder:output_type -> payrail.gateway.v1.CreateOrderResponse
	7,  // 27: payrail.gateway.v1.GatewayService.VerifyWebhook:output_type -> payrail.gateway.v1.VerifyWebhookResponse
	9,  // 28: payrail.gateway.v1.GatewayService.FetchPayment:output_type -> payrail.gateway.v1.FetchPaymentResponse
	11, // 29: payrail.gateway.v1.GatewayService.FetchRefund:output_type -> payrail.gateway.v1.FetchRefundResponse
	13, // 30: payrail.gateway.v1.GatewayService.CapturePayment:output_type -> payrail.gateway.v1.CaptureResponse
	15, // 31: payrail.gateway.v1.GatewayService.CreateRefund:output_type -> payrail.gateway.v1.CreateRefundResponse
	17, // 32: payrail.gateway.v1.GatewayService.FindOrderByReference:output_type -> payrail.gateway.v1.FindOrderByReferenceResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_gateway_v1_gateway_proto_init() }
func file_gateway_v1_gateway_proto_init() {
	if File_gateway_v1_gateway_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gateway_v1_gateway_proto_rawDesc), len(file_gateway_v1_gateway_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_v1_gateway_proto_goTypes,
		DependencyIndexes: file_gateway_v1_gateway_proto_depIdxs,
		EnumInfos:         file_gateway_v1_gateway_proto_enumTypes,
		MessageInfos:      file_gateway_v1_gateway_proto_msgTypes,
	}.Build()
	File_gateway_v1_gateway_proto = out.File
	file_gateway_v1_gateway_proto_goTypes = nil
	file_gateway_v1_gateway_proto_depIdxs = nil
}
