// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: gateway/v1/gateway.proto

package gatewaypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GatewayService_CreateOrder_FullMethodName          = "/payrail.gateway.v1.GatewayService/CreateOrder"
	GatewayService_VerifyWebhook_FullMethodName        = "/payrail.gateway.v1.GatewayService/VerifyWebhook"
	GatewayService_FetchPayment_FullMethodName         = "/payrail.gateway.v1.GatewayService/FetchPayment"
	GatewayService_FetchRefund_FullMethodName          = "/payrail.gateway.v1.GatewayService/FetchRefund"
	GatewayService_CapturePayment_FullMethodName       = "/payrail.gateway.v1.GatewayService/CapturePayment"
	GatewayService_CreateRefund_FullMethodName         = "/payrail.gateway.v1.GatewayService/CreateRefund"
	GatewayService_FindOrderByReference_FullMethodName = "/payrail.gateway.v1.GatewayService/FindOrderByReference"
)

// GatewayServiceClient is the client API for GatewayService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayServiceClient interface {
	CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error)
	VerifyWebhook(ctx context.Context, in *VerifyWebhookRequest, opts ...grpc.CallOption) (*VerifyWebhookResponse, error)
	FetchPayment(ctx context.Context, in *FetchPaymentRequest, opts ...grpc.CallOption) (*FetchPaymentResponse, error)
	FetchRefund(ctx context.Context, in *FetchRefundRequest, opts ...grpc.CallOption) (*FetchRefundResponse, error)
	CapturePayment(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error)
	CreateRefund(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*CreateRefundResponse, error)
	FindOrderByReference(ctx context.Context, in *FindOrderByReferenceRequest, opts ...grpc.CallOption) (*FindOrderByReferenceResponse, error)
}

type gatewayServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayServiceClient(cc grpc.ClientConnInterface) GatewayServiceClient {
	return &gatewayServiceClient{cc}
}

func (c *gatewayServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrderResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) VerifyWebhook(ctx context.Context, in *VerifyWebhookRequest, opts ...grpc.CallOption) (*VerifyWebhookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyWebhookResponse)
	err := c.cc.Invoke(ctx, GatewayService_VerifyWebhook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) FetchPayment(ctx context.Context, in *FetchPaymentRequest, opts ...grpc.CallOption) (*FetchPaymentResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchPaymentResponse)
	err := c.cc.Invoke(ctx, GatewayService_FetchPayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) FetchRefund(ctx context.Context, in *FetchRefundRequest, opts ...grpc.CallOption) (*FetchRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchRefundResponse)
	err := c.cc.Invoke(ctx, GatewayService_FetchRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CapturePayment(ctx context.Context, in *CaptureRequest, opts ...grpc.CallOption) (*CaptureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CaptureResponse)
	err := c.cc.Invoke(ctx, GatewayService_CapturePayment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) CreateRefund(ctx context.Context, in *CreateRefundRequest, opts ...grpc.CallOption) (*CreateRefundResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRefundResponse)
	err := c.cc.Invoke(ctx, GatewayService_CreateRefund_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayServiceClient) FindOrderByReference(ctx context.Context, in *FindOrderByReferenceRequest, opts ...grpc.CallOption) (*FindOrderByReferenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindOrderByReferenceResponse)
	err := c.cc.Invoke(ctx, GatewayService_FindOrderByReference_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServiceServer is the server API for GatewayService service.
// All implementations must embed UnimplementedGatewayServiceServer
// for forward compatibility.
type GatewayServiceServer interface {
	CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)
	VerifyWebhook(context.Context, *VerifyWebhookRequest) (*VerifyWebhookResponse, error)
	FetchPayment(context.Context, *FetchPaymentRequest) (*FetchPaymentResponse, error)
	FetchRefund(context.Context, *FetchRefundRequest) (*FetchRefundResponse, error)
	CapturePayment(context.Context, *CaptureRequest) (*CaptureResponse, error)
	CreateRefund(context.Context, *CreateRefundRequest) (*CreateRefundResponse, error)
	FindOrderByReference(context.Context, *FindOrderByReferenceRequest) (*FindOrderByReferenceResponse, error)
	mustEmbedUnimplementedGatewayServiceServer()
}

// UnimplementedGatewayServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServiceServer struct{}

func (UnimplementedGatewayServiceServer) CreateOrder(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrder not implemented")
}
func (UnimplementedGatewayServiceServer) VerifyWebhook(context.Context, *VerifyWebhookRequest) (*VerifyWebhookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyWebhook not implemented")
}
func (UnimplementedGatewayServiceServer) FetchPayment(context.Context, *FetchPaymentRequest) (*FetchPaymentResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchPayment not implemented")
}
func (UnimplementedGatewayServiceServer) FetchRefund(context.Context, *FetchRefundRequest) (*FetchRefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FetchRefund not implemented")
}
func (UnimplementedGatewayServiceServer) CapturePayment(context.Context, *CaptureRequest) (*CaptureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CapturePayment not implemented")
}
func (UnimplementedGatewayServiceServer) CreateRefund(context.Context, *CreateRefundRequest) (*CreateRefundResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateRefund not implemented")
}
func (UnimplementedGatewayServiceServer) FindOrderByReference(context.Context, *FindOrderByReferenceRequest) (*FindOrderByReferenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindOrderByReference not implemented")
}
func (UnimplementedGatewayServiceServer) mustEmbedUnimplementedGatewayServiceServer() {}
func (UnimplementedGatewayServiceServer) testEmbeddedByValue()                        {}

// UnsafeGatewayServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServiceServer will
// result in compilation errors.
type UnsafeGatewayServiceServer interface {
	mustEmbedUnimplementedGatewayServiceServer()
}

func RegisterGatewayServiceServer(s grpc.ServiceRegistrar, srv GatewayServiceServer) {
	// If the following call panics, it indicates UnimplementedGatewayServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GatewayService_ServiceDesc, srv)
}

func _GatewayService_CreateOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateOrder(ctx, req.(*CreateOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_VerifyWebhook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyWebhookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).VerifyWebhook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_VerifyWebhook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).VerifyWebhook(ctx, req.(*VerifyWebhookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_FetchPayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchPaymentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).FetchPayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_FetchPayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).FetchPayment(ctx, req.(*FetchPaymentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_FetchRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).FetchRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_FetchRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).FetchRefund(ctx, req.(*FetchRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CapturePayment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CaptureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CapturePayment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CapturePayment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CapturePayment(ctx, req.(*CaptureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_CreateRefund_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRefundRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).CreateRefund(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_CreateRefund_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).CreateRefund(ctx, req.(*CreateRefundRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GatewayService_FindOrderByReference_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindOrderByReferenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServiceServer).FindOrderByReference(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GatewayService_FindOrderByReference_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServiceServer).FindOrderByReference(ctx, req.(*FindOrderByReferenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GatewayService_ServiceDesc is the grpc.ServiceDesc for GatewayService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GatewayService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "payrail.gateway.v1.GatewayService",
	HandlerType: (*GatewayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrder",
			Handler:    _GatewayService_CreateOrder_Handler,
		},
		{
			MethodName: "VerifyWebhook",
			Handler:    _GatewayService_VerifyWebhook_Handler,
		},
		{
			MethodName: "FetchPayment",
			Handler:    _GatewayService_FetchPayment_Handler,
		},
		{
			MethodName: "FetchRefund",
			Handler:    _GatewayService_FetchRefund_Handler,
		},
		{
			MethodName: "CapturePayment",
			Handler:    _GatewayService_CapturePayment_Handler,
		},
		{
			MethodName: "CreateRefund",
			Handler:    _GatewayService_CreateRefund_Handler,
		},
		{
			MethodName: "FindOrderByReference",
			Handler:    _GatewayService_FindOrderByReference_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gateway/v1/gateway.proto",
}
